###########################
# Properties local
###########################

###########################
# Configuration
###########################
quarkus.config.locations=config/application-qa.properties


###########################
# Constants custom
###########################
constants.message.example.value=Mensaje de propiedad local