###########################
# Properties DEV
###########################


###########################
# Constants custom
###########################
constants.message.example.value=Mensaje de propiedad DEV