###########################
# Properties QA
###########################


###########################
# Constants custom
###########################
constants.message.example.value=Mensaje de propiedad QA